name: toronto_open_data
version: "1.0.0"
config-version: 2
profile: toronto_open_data

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  toronto_open_data:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table

seeds:
  toronto_open_data:
    +schema: staging
    ttc_delay_codes:
      +column_types:
        delay_code: varchar(10)
